# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flickr < Formula
  desc "Agent-friendly CLI for Flickr photo management, backup, upload, and API access"
  homepage "https://github.com/thedavidweng/flickr-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v0.1.0/flickr_0.1.0_darwin_amd64.tar.gz"
      sha256 "bef3a3b39ff4b6ef4bdfc0e18b28be3f029da68774cb53075336e4127240a90c"

      define_method(:install) do
        bin.install "flickr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v0.1.0/flickr_0.1.0_darwin_arm64.tar.gz"
      sha256 "6c75eb9ed76f8b5d8d0add6b9127fd36d810e149cc9d8bc6c6c4fbc6c06fe9f0"

      define_method(:install) do
        bin.install "flickr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v0.1.0/flickr_0.1.0_linux_amd64.tar.gz"
      sha256 "7024a787cd90a22c65c71ea14ab2fdb864d12585b15aad7cf19cb0d73c54f7b4"
      define_method(:install) do
        bin.install "flickr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v0.1.0/flickr_0.1.0_linux_arm64.tar.gz"
      sha256 "17fa472c6e8c07dbdc6d2191ed0b9401f4081b9a5abbc450a4c7f45f8d158fb9"
      define_method(:install) do
        bin.install "flickr"
      end
    end
  end

  test do
    system "#{bin}/flickr", "version"
  end
end
