# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MonarchmoneyCli < Formula
  desc "A local, agent-friendly CLI for Monarch Money."
  homepage "https://github.com/thedavidweng/monarchmoney-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v0.1.0/monarch_darwin_x86_64.tar.gz"
      sha256 "dcf57fe42f30f53a4f48533b2470bc084e3f99ca53479675ed6675000d6b7c27"

      define_method(:install) do
        bin.install "monarch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v0.1.0/monarch_darwin_arm64.tar.gz"
      sha256 "c959eb3d6ba5279cb7d31cf3e8ed0a65d3adc540494ec09f4ea48a2cc654e392"

      define_method(:install) do
        bin.install "monarch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v0.1.0/monarch_linux_x86_64.tar.gz"
      sha256 "91fe7c625b8a380c90c08a758d28636e6a910939ec7c8c40ffe755043b5e7d7f"
      define_method(:install) do
        bin.install "monarch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v0.1.0/monarch_linux_arm64.tar.gz"
      sha256 "f0b4919499472c3892103f015655d3b695748490130f381f356b037a141f955c"
      define_method(:install) do
        bin.install "monarch"
      end
    end
  end
end
