# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zenodo < Formula
  desc "Agent-friendly CLI for Zenodo deposit management, file upload/download, and InvenioRDM API access"
  homepage "https://github.com/thedavidweng/zenodo-cli"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.3.0/zenodo_0.3.0_darwin_amd64.tar.gz"
      sha256 "3f22de394c4828a39883ef12d28e0808d8fabb6e2ccbbb8c58babd350a7d151f"

      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.3.0/zenodo_0.3.0_darwin_arm64.tar.gz"
      sha256 "7bfacaae5bc54a5ed1420e6b42b21658053eeeb8cfca548a7ffe603f01c656c1"

      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.3.0/zenodo_0.3.0_linux_amd64.tar.gz"
      sha256 "318d96a7ad0deeb4e9d36597d226060a3712ab771893ac2d176e9accb9ef5fe5"
      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.3.0/zenodo_0.3.0_linux_arm64.tar.gz"
      sha256 "2fcf38e084cad0095cd8b225953d7d2107992b2d7826222ae227cefffd418743"
      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
  end

  test do
    system "#{bin}/zenodo", "version"
  end
end
