# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zenodo < Formula
  desc "Agent-friendly CLI for Zenodo deposit management, file upload/download, and InvenioRDM API access"
  homepage "https://github.com/thedavidweng/zenodo-cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.1.1/zenodo_0.1.1_darwin_amd64.tar.gz"
      sha256 "e850f257a614081d8451db40a617d4fa4faa6143bf19bef6285a98527fb07c6c"

      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.1.1/zenodo_0.1.1_darwin_arm64.tar.gz"
      sha256 "95cc830837c2be429ef24a3676a09e52a4b883eda9b52817953e006edc0ed951"

      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.1.1/zenodo_0.1.1_linux_amd64.tar.gz"
      sha256 "eb53d48b65e96e649db6b60821b76fbd403363dcaa26540065995de844b5d871"
      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.1.1/zenodo_0.1.1_linux_arm64.tar.gz"
      sha256 "28c134316efc0b8f9bfd950ad16696b28452bda6da1f5ac0bb7394ffaf5f98aa"
      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
  end

  test do
    system "#{bin}/zenodo", "version"
  end
end
