# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zenodo < Formula
  desc "Agent-friendly CLI for Zenodo deposit management, file upload/download, and InvenioRDM API access"
  homepage "https://github.com/thedavidweng/zenodo-cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.1.1/zenodo_0.1.1_darwin_amd64.tar.gz"
      sha256 "6ad6d158cfcef48d221b5d2a3593507e825aa1b70c0664401314893e50a84ecc"

      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.1.1/zenodo_0.1.1_darwin_arm64.tar.gz"
      sha256 "b8f4af9bce4d5d1e3b8d4fb2f088ad0a65dceafcb18b4207f3dcdfa23be13007"

      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.1.1/zenodo_0.1.1_linux_amd64.tar.gz"
      sha256 "1b0ca47f13799b11aa0b2da89311bca98bcd3957825c508b56cef843943f6ead"
      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v0.1.1/zenodo_0.1.1_linux_arm64.tar.gz"
      sha256 "51be9c85ee9f63f29e8ef017a50dd4e10e96c30ee4bd2096e7398f2cc6bd6a18"
      define_method(:install) do
        bin.install "zenodo"
        generate_completions_from_executable(bin/"zenodo", "completion")
      end
    end
  end

  test do
    system "#{bin}/zenodo", "version"
  end
end
