import importlib.util
import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
SCRIPT_PATH = ROOT / "scripts" / "normalize_cask_style.py"

HEADER = "# This file was generated by GoReleaser. DO NOT EDIT.\n"

# What `brew style --fix --except-cops Cask/StanzaOrder` leaves behind for a
# GoReleaser cask using `custom_block`: the postflight block still at the top
# (its canonical position was excluded from autocorrect) and `on_intel` still
# ahead of `on_arm`.
STYLE_FIXED = HEADER + """cask "ztest" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ztest"]
    end
  end

  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "aa"
      url "https://example.com/x-intel.tar.gz"
    end
    on_arm do
      sha256 "bb"
      url "https://example.com/x-arm.tar.gz"
    end
  end

  name "ztest"
  desc "Test cask"
  homepage "https://example.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ztest"

  # No zap stanza required

end
"""

# The quarantine removal must land *before* `generate_completions_from_executable`,
# because that stanza executes the not-yet-notarized binary.
WITH_COMPLETIONS = HEADER + """cask "ztest" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ztest"]
    end
  end

  version "1.0.0"

  name "ztest"
  desc "Test cask"
  homepage "https://example.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ztest"

  generate_completions_from_executable "ztest", "completion",
                                       shell_parameter_format: :cobra,
                                       shells:                 [:bash, :zsh, :fish]

  # No zap stanza required

end
"""

# Two inverted `on_<os>` blocks, as `brew style --fix` only corrects the first.
TWO_INVERSIONS = HEADER + """cask "ztest" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "aa"
      url "https://example.com/m-intel.tar.gz"
    end
    on_arm do
      sha256 "bb"
      url "https://example.com/m-arm.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "cc"
      url "https://example.com/l-intel.tar.gz"
    end
    on_arm do
      sha256 "dd"
      url "https://example.com/l-arm.tar.gz"
    end
  end

  name "ztest"
  desc "Test cask"
  homepage "https://example.com"

  binary "ztest"
end
"""


def load_module():
    if not SCRIPT_PATH.exists():
        raise AssertionError(f"missing script: {SCRIPT_PATH}")

    spec = importlib.util.spec_from_file_location("normalize_cask_style", SCRIPT_PATH)
    if spec is None or spec.loader is None:
        raise AssertionError(f"unable to load script: {SCRIPT_PATH}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class NormalizeCaskStyleTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.mod = load_module()

    def test_moves_block_after_binary(self):
        out, changed = self.mod.normalise(STYLE_FIXED)
        self.assertTrue(changed)
        self.assertLess(out.index('  binary "ztest"'), out.index("  postflight_steps do"))
        self.assertLess(out.index("  postflight_steps do"), out.index("  # No zap stanza required"))

    def test_orders_arm_before_intel(self):
        out, changed = self.mod.normalise(STYLE_FIXED)
        self.assertTrue(changed)
        self.assertLess(out.index("    on_arm do"), out.index("    on_intel do"))

    def test_fixes_every_inverted_arch_block(self):
        out, _ = self.mod.normalise(TWO_INVERSIONS)
        self.assertLess(out.index("    on_arm do"), out.index("    on_intel do"))
        self.assertLess(out.rindex("    on_arm do"), out.rindex("    on_intel do"))

    def test_block_precedes_completion_generation(self):
        out, changed = self.mod.normalise(WITH_COMPLETIONS)
        self.assertTrue(changed)
        self.assertLess(
            out.index("  postflight_steps do"),
            out.index("  generate_completions_from_executable"),
        )

    def test_is_idempotent(self):
        once, _ = self.mod.normalise(STYLE_FIXED)
        twice, changed = self.mod.normalise(once)
        self.assertFalse(changed)
        self.assertEqual(once, twice)

    def test_settles_in_a_single_pass(self):
        # `brew style --fix` corrects only the first inversion, so the script
        # has to iterate internally rather than need a second invocation.
        out, _ = self.mod.normalise(TWO_INVERSIONS)
        self.assertEqual(out, self.mod.normalise(out)[0])

    def test_leaves_correct_cask_untouched(self):
        good = HEADER + (
            'cask "ztest" do\n  version "1.0.0"\n\n'
            '  name "ztest"\n  desc "Test cask"\n  homepage "https://example.com"\n\n'
            '  binary "ztest"\n\n'
            "  postflight_steps do\n    on_macos do\n"
            '      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ztest"]\n'
            "    end\n  end\n\n"
            "  # No zap stanza required\nend\n"
        )
        out, changed = self.mod.normalise(good)
        self.assertFalse(changed)
        self.assertEqual(good, out)

    def test_does_not_touch_hand_written_casks(self):
        hand_written = HEADER + 'cask "ztest" do\n  version "1.0.0"\n\n  app "Ztest.app"\nend\n'
        out, changed = self.mod.normalise(hand_written)
        self.assertFalse(changed)
        self.assertEqual(hand_written, out)

    def test_no_blank_line_at_cask_body_start(self):
        out, _ = self.mod.normalise(STYLE_FIXED)
        self.assertNotIn('cask "ztest" do\n\n', out)

    def test_no_blank_line_before_closing_end(self):
        out, _ = self.mod.normalise(STYLE_FIXED)
        self.assertNotIn("\n\nend\n", out)

    def test_preserves_trailing_newline(self):
        out, _ = self.mod.normalise(STYLE_FIXED)
        self.assertTrue(out.endswith("\n"))
        self.assertFalse(out.endswith("\n\n"))


if __name__ == "__main__":
    unittest.main()
