import importlib.util
import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
SCRIPT_PATH = ROOT / "scripts" / "normalize_cask_style.py"

HEADER = "# This file was generated by GoReleaser. DO NOT EDIT.\n"

# Exactly what GoReleaser renders for a cask using `custom_block`: the block is
# emitted immediately after `cask ... do`, above `version`.
LEADING = HEADER + """cask "ztest" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ztest"]
    end
  end

  version "1.0.0"

  name "ztest"
  desc "Test cask"
  homepage "https://example.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ztest"

  # No zap stanza required

end
"""

# The quarantine removal must land *before* `generate_completions_from_executable`,
# because that stanza executes the not-yet-notarized binary.
WITH_COMPLETIONS = HEADER + """cask "ztest" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ztest"]
    end
  end

  version "1.0.0"

  name "ztest"
  desc "Test cask"
  homepage "https://example.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ztest"

  generate_completions_from_executable "ztest", "completion",
                                       shell_parameter_format: :cobra,
                                       shells:                 [:bash, :zsh, :fish]

  # No zap stanza required

end
"""


def load_module():
    if not SCRIPT_PATH.exists():
        raise AssertionError(f"missing script: {SCRIPT_PATH}")

    spec = importlib.util.spec_from_file_location("normalize_cask_style", SCRIPT_PATH)
    if spec is None or spec.loader is None:
        raise AssertionError(f"unable to load script: {SCRIPT_PATH}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class NormalizeCaskStyleTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.mod = load_module()

    def test_moves_block_after_binary(self):
        out, changed = self.mod.normalise(LEADING)
        self.assertTrue(changed)
        self.assertIn('  postflight_steps do\n', out)
        # The block must follow `binary`, not precede `version`.
        self.assertLess(out.index('  binary "ztest"'), out.index("  postflight_steps do"))
        self.assertLess(out.index("  postflight_steps do"), out.index("  # No zap stanza required"))

    def test_block_precedes_completion_generation(self):
        out, changed = self.mod.normalise(WITH_COMPLETIONS)
        self.assertTrue(changed)
        self.assertLess(
            out.index("  postflight_steps do"),
            out.index("  generate_completions_from_executable"),
        )

    def test_is_idempotent(self):
        once, _ = self.mod.normalise(LEADING)
        twice, changed = self.mod.normalise(once)
        self.assertFalse(changed)
        self.assertEqual(once, twice)

    def test_leaves_normalised_cask_untouched(self):
        normalised, _ = self.mod.normalise(LEADING)
        again, changed = self.mod.normalise(normalised)
        self.assertFalse(changed)
        self.assertEqual(normalised, again)

    def test_does_not_touch_hand_written_casks(self):
        hand_written = HEADER + 'cask "ztest" do\n  version "1.0.0"\n\n  app "Ztest.app"\nend\n'
        out, changed = self.mod.normalise(hand_written)
        self.assertFalse(changed)
        self.assertEqual(hand_written, out)

    def test_preserves_trailing_newline(self):
        out, _ = self.mod.normalise(LEADING)
        self.assertTrue(out.endswith("\n"))
        self.assertFalse(out.endswith("\n\n"))


if __name__ == "__main__":
    unittest.main()
