# This file was generated by GoReleaser. DO NOT EDIT.
cask "canvas" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "392283317e90575451cac99e92c1033da257604177dd9c908060fa0da64353a8"
      url "https://github.com/thedavidweng/canvas-cli/releases/download/v#{version}/canvas_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cdda90b6ce297276802afa7e3f0dbf1814f008730f38661ad26acd8b6355ce07"
      url "https://github.com/thedavidweng/canvas-cli/releases/download/v#{version}/canvas_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "709a5ddf18d51423c204af7c253c5167e39139d73c1562aedfb764758c9d342c"
      url "https://github.com/thedavidweng/canvas-cli/releases/download/v#{version}/canvas_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "88d645e21fbe951a5bb9f0abff96987919dd13f21f0e59fc0c7e09d6cf4c5a1b"
      url "https://github.com/thedavidweng/canvas-cli/releases/download/v#{version}/canvas_#{version}_linux_arm64.tar.gz"
    end
  end

  name "canvas"
  desc "Agent-friendly CLI for Canvas LMS course management, assignments, submissions, and more"
  homepage "https://github.com/thedavidweng/canvas-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "canvas"

  generate_completions_from_executable "canvas", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
