# This file was generated by GoReleaser. DO NOT EDIT.
cask "canvas" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2748cc8733b6b01c9d57d777f9e09868c70e6e43075ffc009241f15472e3a0e6"
      url "https://github.com/thedavidweng/canvas-cli/releases/download/v#{version}/canvas_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c5d6e571d1102fc94b0d005dad9852b81f703f3402dfb0acce85a6d27405419"
      url "https://github.com/thedavidweng/canvas-cli/releases/download/v#{version}/canvas_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "36a2eb1f8874f756dcfbd747e8e53ff20ea77a99751cf56aaecbe5ef6f0c7101"
      url "https://github.com/thedavidweng/canvas-cli/releases/download/v#{version}/canvas_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6c3411fefaea1ba0a74d8a7c6457a288897a5ebd472e519c2139f2438a3cbf8"
      url "https://github.com/thedavidweng/canvas-cli/releases/download/v#{version}/canvas_#{version}_linux_arm64.tar.gz"
    end
  end

  name "canvas"
  desc "Agent-friendly CLI for Canvas LMS course management, assignments, submissions, and more"
  homepage "https://github.com/thedavidweng/canvas-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "canvas"

  generate_completions_from_executable "canvas", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
