# This file was generated by GoReleaser. DO NOT EDIT.
cask "flickr" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "efc7c165fe0e94348e47924bfb9722f65c2c96d1210e246fce6ddfa4f6c05079"
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v#{version}/flickr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8464159d49e52697520482b2f2db4a75d4ac0f233abe08240fbcda4ff0ff69b9"
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v#{version}/flickr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "552a26153a06eb781b2d5cacda4fe2a18a7a0afa4d188b588734d013e928f1d8"
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v#{version}/flickr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a23b809505a8993777b0523c0639244b620df50bc14ed534c05194f6ec7c8307"
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v#{version}/flickr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "flickr"
  desc "Agent-friendly CLI for Flickr photo management, backup, upload, and API access"
  homepage "https://github.com/thedavidweng/flickr-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flickr"

  generate_completions_from_executable "flickr", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
