# This file was generated by GoReleaser. DO NOT EDIT.
cask "flickr" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "660699f263dd00e9fc11b9e14f679a052f50803a70ec4982e4abdb19f630c5b5"
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v#{version}/flickr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "24bad16af5fa0f0c594dae99d03dc8deba8d152b4f2de3fa930fe6e55f632005"
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v#{version}/flickr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "21bad1675c58bf1f0fc7badcf325da7352b231c4fbdc54ba6fd60f0fc03f87a2"
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v#{version}/flickr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dad94f8d6e24c368a15edaf2d3d629d66b81329bb76e2c8d3d7f9f7437595346"
      url "https://github.com/thedavidweng/flickr-cli/releases/download/v#{version}/flickr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flickr"
  desc "Agent-friendly CLI for Flickr photo management, backup, upload, and API access"
  homepage "https://github.com/thedavidweng/flickr-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flickr"

  generate_completions_from_executable "flickr", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
