# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobs-cli" do
  version "2.0.1"

  on_macos do
    sha256 "7aa4d2d637f2356b055796e5d464c15a9e349f8ca678ab5d62b1a68bbfbed3da"
    url "https://github.com/thedavidweng/jobs-cli/releases/download/v#{version}/jobs-cli_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "5373dc10a27fb44c4388219aa97f1b3356c980cf81fd8ef6b15014f7d73ade65"
      url "https://github.com/thedavidweng/jobs-cli/releases/download/v#{version}/jobs-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b71556c69f208de291672753d673465df6db785a64c080197ecc7e090f67469"
      url "https://github.com/thedavidweng/jobs-cli/releases/download/v#{version}/jobs-cli_linux_x86_64.tar.gz"
    end
  end

  name "jobs-cli"
  desc "Agent-friendly CLI for job discovery and applications"
  homepage "https://github.com/thedavidweng/jobs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobs-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jobs-cli"]
    end
  end

  # No zap stanza required
end
