# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobs-cli" do
  version "2.0.0"

  on_macos do
    sha256 "23b9a7604f989599897db7e5f998a20b1ecd0df8d4ea61646c0a5953ee58923a"
    url "https://github.com/thedavidweng/jobs-cli/releases/download/v#{version}/jobs-cli_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "934e48513367acb7982de44656b66c2c47cf168072ab8d19f23d356ee3620d94"
      url "https://github.com/thedavidweng/jobs-cli/releases/download/v#{version}/jobs-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fefcd668fd77740798623b5e7d66c2bfe5076eb3a90e18bda7fec9719f156723"
      url "https://github.com/thedavidweng/jobs-cli/releases/download/v#{version}/jobs-cli_linux_x86_64.tar.gz"
    end
  end

  name "jobs-cli"
  desc "Agent-friendly CLI for job discovery and applications"
  homepage "https://github.com/thedavidweng/jobs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobs-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jobs-cli"]
    end
  end

  # No zap stanza required
end
