# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobs-cli" do
  version "2.0.2"

  on_macos do
    sha256 "66edfd2ffcd9a6d0e5aa2648b74a8d90bd53acd0ee6718e6476348878b0ca3fb"
    url "https://github.com/thedavidweng/jobs-cli/releases/download/v#{version}/jobs-cli_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "6239a139a6d80440b31ef3227ca63f048c0ef963ff4f5d0ea224ac3439c4408b"
      url "https://github.com/thedavidweng/jobs-cli/releases/download/v#{version}/jobs-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "976859c10217f25615c4d2b09645f5f7f781cf1eae963afafef5231f279f4536"
      url "https://github.com/thedavidweng/jobs-cli/releases/download/v#{version}/jobs-cli_linux_x86_64.tar.gz"
    end
  end

  name "jobs-cli"
  desc "Agent-friendly CLI for job discovery and applications"
  homepage "https://github.com/thedavidweng/jobs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobs-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jobs-cli"]
    end
  end

  # No zap stanza required
end
