# This file was generated by GoReleaser. DO NOT EDIT.
cask "monarchmoney-cli" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "ce54eff05eb4eedba5a63f9c972748d7247d5070430b765bd7a6f198a9a18db2"
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v#{version}/monarch_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "acb707a1ead0a7809539f3ff9801c77eeba58b028c48d120f913e337f9b4e31b"
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v#{version}/monarch_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "77630c824bc7436be54f2d3ed095ecb82fb2b927997448ed71b52d94b68b6837"
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v#{version}/monarch_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4da4d127cea177b10f760b5f04e85f05a97f05660d42209a62054390d038f016"
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v#{version}/monarch_linux_arm64.tar.gz"
    end
  end

  name "monarchmoney-cli"
  desc "Local, agent-friendly CLI for Monarch Money"
  homepage "https://github.com/thedavidweng/monarchmoney-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monarch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monarch"]
    end
  end

  # No zap stanza required

end
