# This file was generated by GoReleaser. DO NOT EDIT.
cask "monarchmoney-cli" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/monarch"]
    end
  end

  version "0.12.0"

  on_macos do
    sha256 "43ac73d85cad707266eb0c0263eebd74746084836be41fbd2170b7dbeb1539f1"
    url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v#{version}/monarch_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "e0c0a66358f3679568e3d6cd0338d75ccd9cf018f9b993b5d95a40467c52efdd"
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v#{version}/monarch_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f6a40ba5456bb8e7b0fdeaad8433f9e3ba41b1bd3c8ff4b392df1a6c704e90ef"
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v#{version}/monarch_linux_x86_64.tar.gz"
    end
  end

  name "monarchmoney-cli"
  desc "Local, agent-friendly CLI for Monarch Money"
  homepage "https://github.com/thedavidweng/monarchmoney-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monarch"

  # No zap stanza required
end
