# This file was generated by GoReleaser. DO NOT EDIT.
cask "monarchmoney-cli" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "a36560c918442fb612b8b6bee7193d73a58d3978a00f05e9feb42bd1832d49b8"
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v#{version}/monarch_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "590870e2dcf0dd9736d30ab8ed740743dbe2bcd705f32ca192521fcb6033394d"
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v#{version}/monarch_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "49a10ab1a038ae799409b68a82459f838131fb4d61e9af47af3483f20361f6d5"
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v#{version}/monarch_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c4fbab826392259d98378ecc0711b0c33d894527d6b109dc6658f1730ad37d46"
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v#{version}/monarch_linux_arm64.tar.gz"
    end
  end

  name "monarchmoney-cli"
  desc "Local, agent-friendly CLI for Monarch Money"
  homepage "https://github.com/thedavidweng/monarchmoney-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monarch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monarch"]
    end
  end

  # No zap stanza required

end
