# This file was generated by GoReleaser. DO NOT EDIT.
cask "money" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "dad5e8aa61fc5093aa206349d1723fef6378268c24c2c59ae078b93e26e83626"
      url "https://github.com/thedavidweng/money/releases/download/v#{version}/money_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "55917659d8588cdafcfa6a7154fe010d94217912ed28f2478a161145e0f60b1b"
      url "https://github.com/thedavidweng/money/releases/download/v#{version}/money_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e225ecd7596951cfe7aedd9f84a9925caf5e7b59c524dc34e41186c9f3a6dc51"
      url "https://github.com/thedavidweng/money/releases/download/v#{version}/money_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1758414a9417cb1646d9261566429a7b2082490888391f0dd41c17e9b67928e"
      url "https://github.com/thedavidweng/money/releases/download/v#{version}/money_#{version}_linux_arm64.tar.gz"
    end
  end

  name "money"
  desc "Local-first personal finance backend for agents and power users"
  homepage "https://github.com/thedavidweng/money"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "money"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/money"]
    end
  end

  # No zap stanza required

end
