# This file was generated by GoReleaser. DO NOT EDIT.
cask "money" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "b540b820b5371b7b41f95e9761fb15fb81366188676f291bca1e9ce9c8970180"
      url "https://github.com/thedavidweng/money/releases/download/v#{version}/money_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "299e706d7236c39b5bd2f196f8c168f25bc94749d13c64f87ca5e29a94f56a49"
      url "https://github.com/thedavidweng/money/releases/download/v#{version}/money_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "52332bbbfd729b9413000b8a3d549565ae7250a9e8edbbbd34f286484915eb6f"
      url "https://github.com/thedavidweng/money/releases/download/v#{version}/money_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b65790ff36004244a27472253087ae3024b7da0081d8b5eb46481df4118f2ac"
      url "https://github.com/thedavidweng/money/releases/download/v#{version}/money_#{version}_linux_arm64.tar.gz"
    end
  end

  name "money"
  desc "Local-first personal finance backend for agents and power users"
  homepage "https://github.com/thedavidweng/money"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "money"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/money"]
    end
  end

  # No zap stanza required

end
