# This file was generated by GoReleaser. DO NOT EDIT.
cask "qualtrics" do
  version "0.1.0"

  on_macos do
    sha256 "803b6a1376a942e1464b22613d289f4584c280ef461d27838ffc6cfc1a34b510"
    url "https://github.com/thedavidweng/qualtrics-cli/releases/download/v#{version}/qualtrics_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "3cf7ad82aa00faf5d98e94298ecda5aafb072c578cd43ac47864c19a2faa041f"
      url "https://github.com/thedavidweng/qualtrics-cli/releases/download/v#{version}/qualtrics_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cfe1e19a7d9fa2d9ae01b0a626ff7957fe3b0372d89c322fd4ed5bf63283f85e"
      url "https://github.com/thedavidweng/qualtrics-cli/releases/download/v#{version}/qualtrics_linux_x86_64.tar.gz"
    end
  end

  name "qualtrics"
  desc "Agent-friendly CLI for the Qualtrics Experience Management Platform & offline survey compiler"
  homepage "https://github.com/thedavidweng/qualtrics-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qualtrics"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qualtrics"]
    end
  end
  generate_completions_from_executable "qualtrics", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
