# This file was generated by GoReleaser. DO NOT EDIT.
cask "qualtrics" do
  version "0.1.0"

  on_macos do
    sha256 "6316f02e0e48b6a01eb7d03f354dfa8d2822f6433f109240dd61ba37cd2644ad"
    url "https://github.com/thedavidweng/qualtrics-cli/releases/download/v#{version}/qualtrics_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "1142b94669af4b73f2fc55840022ac570ff55ed2ab339a7d7af075a9149bd140"
      url "https://github.com/thedavidweng/qualtrics-cli/releases/download/v#{version}/qualtrics_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8d027ba5ff9dc23c1e2f3bb0a932294ea19f8bfa55714aa4474d4ee11ac2b73"
      url "https://github.com/thedavidweng/qualtrics-cli/releases/download/v#{version}/qualtrics_linux_x86_64.tar.gz"
    end
  end

  name "qualtrics"
  desc "Agent-friendly CLI for the Qualtrics Experience Management Platform & offline survey compiler"
  homepage "https://github.com/thedavidweng/qualtrics-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qualtrics"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qualtrics"]
    end
  end
  generate_completions_from_executable "qualtrics", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
