# This file was generated by GoReleaser. DO NOT EDIT.
cask "qualtrics" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/qualtrics"]
    end
  end

  version "0.2.1"

  on_macos do
    sha256 "117fd18aa96d12e54795cf7690ce6f985af90a7cd940b6494d281760270a2bfa"
    url "https://github.com/thedavidweng/qualtrics-cli/releases/download/v#{version}/qualtrics_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "eb851b48f8ab7863ff2676db1cb9c07880ff56163b50f334ea76bbfc86c1fc63"
      url "https://github.com/thedavidweng/qualtrics-cli/releases/download/v#{version}/qualtrics_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b8af7c5fa6b37e44295e2152a9595a7d354ca8b7d799ba8d41b59e5b5db68ed"
      url "https://github.com/thedavidweng/qualtrics-cli/releases/download/v#{version}/qualtrics_linux_x86_64.tar.gz"
    end
  end

  name "qualtrics"
  desc "Agent-friendly CLI for the Qualtrics survey platform"
  homepage "https://github.com/thedavidweng/qualtrics-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qualtrics"

  generate_completions_from_executable "qualtrics", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
