# This file was generated by GoReleaser. DO NOT EDIT.
cask "zenodo" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "6ad6d158cfcef48d221b5d2a3593507e825aa1b70c0664401314893e50a84ecc"
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v#{version}/zenodo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b8f4af9bce4d5d1e3b8d4fb2f088ad0a65dceafcb18b4207f3dcdfa23be13007"
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v#{version}/zenodo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b0ca47f13799b11aa0b2da89311bca98bcd3957825c508b56cef843943f6ead"
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v#{version}/zenodo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "51be9c85ee9f63f29e8ef017a50dd4e10e96c30ee4bd2096e7398f2cc6bd6a18"
      url "https://github.com/thedavidweng/zenodo-cli/releases/download/v#{version}/zenodo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zenodo"
  desc "Agent-friendly CLI for Zenodo deposit management, file upload/download, and InvenioRDM API access"
  homepage "https://github.com/thedavidweng/zenodo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zenodo"

  generate_completions_from_executable "zenodo", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
