# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MonarchmoneyCli < Formula
  desc "A local, agent-friendly CLI for Monarch Money."
  homepage "https://github.com/thedavidweng/monarchmoney-cli"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v0.3.1/monarch_darwin_x86_64.tar.gz"
      sha256 "98be7f407828dab213040323ca99011bb82f5d83e6972ed772bd727641e29161"

      define_method(:install) do
        bin.install "monarch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v0.3.1/monarch_darwin_arm64.tar.gz"
      sha256 "79aacd2e034d483e2c47ea71c09e18806113002c431aecd752b60e79c8c0ee7d"

      define_method(:install) do
        bin.install "monarch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v0.3.1/monarch_linux_x86_64.tar.gz"
      sha256 "8073404b5540cd55c0a6410e4ec8f0e3f06bac136018cdc069251b8c8e818581"
      define_method(:install) do
        bin.install "monarch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thedavidweng/monarchmoney-cli/releases/download/v0.3.1/monarch_linux_arm64.tar.gz"
      sha256 "1b66f00f08888d7cfdf998a179b71b2db2bcd79a9e93118ce37511f20761e487"
      define_method(:install) do
        bin.install "monarch"
      end
    end
  end
end
