# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Money < Formula
  desc "A local-first, self-hostable personal finance backend for AI agents and power users."
  homepage "https://github.com/thedavidweng/money"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/thedavidweng/money/releases/download/v0.1.0/money_0.1.0_darwin_amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"

      def install
        bin.install "money"
      end
    end
    on_arm do
      url "https://github.com/thedavidweng/money/releases/download/v0.1.0/money_0.1.0_darwin_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"

      def install
        bin.install "money"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thedavidweng/money/releases/download/v0.1.0/money_0.1.0_linux_amd64.tar.gz"
        sha256 "0000000000000000000000000000000000000000000000000000000000000000"

        def install
          bin.install "money"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thedavidweng/money/releases/download/v0.1.0/money_0.1.0_linux_arm64.tar.gz"
        sha256 "0000000000000000000000000000000000000000000000000000000000000000"

        def install
          bin.install "money"
        end
      end
    end
  end

  test do
    system "#{bin}/money", "version"
  end
end
