#!/usr/bin/env python3
"""
Normalise GoReleaser-generated casks in this tap to Homebrew's current style.

Why this exists
---------------
Several casks here are generated by GoReleaser (`# This file was generated by
GoReleaser. DO NOT EDIT.`), and GoReleaser's cask template still emits
Homebrew's deprecated `preflight`/`postflight` stanzas. Upstream issue:
goreleaser/goreleaser#6873. The source repos work around this by emitting a
`postflight_steps` block through `homebrew_casks[].custom_block`, because the
new install-steps DSL is the only spelling Homebrew accepts without warnings.

GoReleaser renders `custom_block` at the very top of the cask, which violates
`Cask/StanzaOrder`. The obvious fix — running `brew style --fix` — is wrong for
`qualtrics`: that cask's `generate_completions_from_executable` stanza executes
the staged binary, and the release is not notarized, so running it while the
binary is still quarantined gets it SIGKILLed by Gatekeeper (exit 137). The
quarantine removal therefore has to run *before* the completion stanza, which is
the opposite of Homebrew's canonical stanza order.

So this script performs a targeted move of the `postflight_steps` block only,
and leaves everything else (including the deliberate ordering exception)
untouched. It is idempotent: a cask that is already normalised is left alone.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CASK_DIR = ROOT / "Casks"

GENERATED_MARKER = "# This file was generated by GoReleaser. DO NOT EDIT."

# The block GoReleaser renders from `custom_block`, at the top of the cask.
LEADING_POSTFLIGHT = re.compile(
    r"\A(?P<head># [^\n]*\n)cask \"(?P<token>[^\"]+)\" do\n"
    r"(?P<block>  postflight_steps do\n(?:.*?\n)  end\n)\n",
    re.S,
)

# Where the block belongs. `generate_completions_from_executable` executes the
# staged binary, so it must come after the quarantine removal; everything else
# follows Homebrew's canonical stanza order. GoReleaser's trailing
# `# No zap stanza required` placeholder is treated as a follower too, so the
# block never lands after it.
FOLLOWERS = (
    "generate_completions_from_executable",
    "uninstall_preflight_steps",
    "uninstall_preflight",
    "uninstall_postflight_steps",
    "uninstall_postflight",
    "uninstall",
    "zap",
    "caveats",
    "# No zap stanza required",
)
FOLLOWER_RE = re.compile(r"^  (?:" + "|".join(re.escape(f) for f in FOLLOWERS) + r")\b", re.M)


def normalise(text):
    """Move a leading `postflight_steps` block to its correct stanza position."""
    match = LEADING_POSTFLIGHT.match(text)
    if not match:
        return text, False

    block = match.group("block")
    remainder = text[match.end():]

    follower = FOLLOWER_RE.search(remainder)
    if follower:
        before = remainder[:follower.start()].rstrip()
        after = remainder[follower.start():].lstrip("\n")
        rebuilt = f"{match.group('head')}cask \"{match.group('token')}\" do\n{before}\n\n{block}\n{after}"
    else:
        # No later stanza to anchor on: append just before the closing `end`.
        parts = remainder.rstrip("\n").rsplit("\nend", 1)
        if len(parts) != 2:
            return text, False
        rebuilt = (
            f"{match.group('head')}cask \"{match.group('token')}\" do\n"
            f"{parts[0].rstrip()}\n\n{block}\nend{parts[1]}"
        )

    if not rebuilt.endswith("\n"):
        rebuilt += "\n"
    # GoReleaser leaves a blank line before the cask's closing `end`, which
    # `Layout/EmptyLinesAroundBlockBody` rejects.
    rebuilt = re.sub(r"\n+\Z", "\n", rebuilt)
    return rebuilt, True


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    paths = [pathlib.Path(p) for p in argv] if argv else sorted(CASK_DIR.glob("*.rb"))

    changed = []
    for path in paths:
        text = original = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in text:
            continue
        text, did_change = normalise(text)
        if did_change and text != original:
            path.write_text(text, encoding="utf-8")
            changed.append(path.name)

    if changed:
        print(f"Normalised {len(changed)} cask(s): {', '.join(changed)}")
    else:
        print("No casks needed normalising.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
