#!/usr/bin/env python3
"""
Normalise GoReleaser-generated casks in this tap to Homebrew's current style.

Why this exists
---------------
Several casks here are generated by GoReleaser (`# This file was generated by
GoReleaser. DO NOT EDIT.`). Two things about its output need fixing up, and
neither can be handled by the obvious `brew style --fix`:

1. GoReleaser's cask template still emits Homebrew's deprecated
   `preflight`/`postflight` stanzas (upstream goreleaser/goreleaser#6873). The
   source repos work around this by emitting a `postflight_steps` block through
   `homebrew_casks[].custom_block`, since the install-steps DSL is the only
   spelling Homebrew accepts without a deprecation warning. GoReleaser renders
   `custom_block` at the very top of the cask, out of stanza order.

2. GoReleaser emits `on_intel` before `on_arm`; Homebrew's canonical order is
   the reverse.

`brew style --fix` sorts the arch blocks correctly, but it also "corrects" the
stanza order by moving `generate_completions_from_executable` *above* the
quarantine removal. That is wrong here: the completion stanza executes the
staged binary, and these releases are not notarized, so running it while the
binary is still quarantined gets it SIGKILLed by Gatekeeper. Verified against a
real release: quarantined binary hangs/is killed, de-quarantined binary exits 0.

So the pipeline is `brew style --fix --except-cops Cask/StanzaOrder` followed by
this script, which re-orders only the blocks that need to move and leaves the
deliberate `qualtrics` exception intact. The script is idempotent.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CASK_DIR = ROOT / "Casks"

GENERATED_MARKER = "# This file was generated by GoReleaser. DO NOT EDIT."

# A `postflight_steps` block, wherever it currently sits in the cask.
POSTFLIGHT_BLOCK = re.compile(r"^  postflight_steps do\n(?:.*?\n)  end\n", re.M | re.S)

# Where the block belongs. `generate_completions_from_executable` executes the
# staged binary, so it must come *after* the quarantine removal; the rest
# follows Homebrew's canonical stanza order. GoReleaser's trailing
# `# No zap stanza required` placeholder counts as a follower too, so the block
# never lands after it.
FOLLOWERS = (
    "generate_completions_from_executable",
    "uninstall_preflight_steps",
    "uninstall_preflight",
    "uninstall_postflight_steps",
    "uninstall_postflight",
    "uninstall",
    "zap",
    "caveats",
    "# No zap stanza required",
)
FOLLOWER_RE = re.compile(r"^  (?:" + "|".join(re.escape(f) for f in FOLLOWERS) + r")\b", re.M)

# Homebrew wants `on_arm` before `on_intel` within an `on_<os>` block.
ON_INTEL_RE = re.compile(r"^(?P<indent>[ ]*)on_intel do\n", re.M)

# Upper bound on fixpoint iterations; a cask has at most a handful of
# `on_<os>` blocks, so this only guards against a rewrite cycle.
MAX_PASSES = 20


def move_postflight(text):
    """Move the cask's `postflight_steps` block to just before its first follower."""
    match = POSTFLIGHT_BLOCK.search(text)
    if not match:
        return text, False

    block = match.group(0)
    without = text[: match.start()] + text[match.end():]

    follower = FOLLOWER_RE.search(without)
    if not follower:
        return text, False

    before = without[: follower.start()].rstrip()
    after = without[follower.start():].lstrip("\n")
    rebuilt = f"{before}\n\n{block}\n{after}"
    return _tidy(rebuilt), True


def order_arch_blocks(text):
    """Swap an `on_intel do` block that precedes its `on_arm` sibling."""
    for intel in ON_INTEL_RE.finditer(text):
        indent = intel.group("indent")
        # Find the end of the on_intel block by brace-free indentation matching.
        end = _block_end(text, intel.end() - len("on_intel do\n"), indent)
        arm = re.compile(
            r"^" + re.escape(indent) + r"on_arm do\n(?:.*?\n)^" + re.escape(indent) + r"end\n",
            re.M | re.S,
        ).search(text, intel.end())
        if not arm or arm.start() > end:
            continue
        intel_block = text[intel.start():end]
        arm_block = text[arm.start():arm.end()]
        return text[: intel.start()] + arm_block + intel_block + text[arm.end():], True
    return text, False


def _block_end(text, body_start, indent):
    """Return the index just past the `end` closing a block opened at `body_start`."""
    closer = re.compile(r"^" + re.escape(indent) + r"end\n", re.M)
    match = closer.search(text, body_start)
    return match.end() if match else body_start


def _tidy(text):
    # Collapse the blank lines an extraction leaves behind, keep exactly one
    # blank line between stanzas, and drop the blank lines GoReleaser leaves at
    # the start and end of the cask body (`Layout/EmptyLinesAroundBlockBody`
    # rejects both).
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r'(cask "[^"]+" do)\n+', r"\1\n", text)
    text = re.sub(r"\n\n+(end\n)\Z", r"\n\1", text)
    if not text.endswith("\n"):
        text += "\n"
    return text


def normalise(text):
    # Both passes can expose further work: moving the postflight block reveals
    # arch blocks underneath it, and `brew style --fix` only corrects the first
    # `on_intel`/`on_arm` inversion in a file. Iterate until the text settles.
    original = text
    for _ in range(MAX_PASSES):
        text, moved = move_postflight(text)
        text, swapped = order_arch_blocks(text)
        if not (moved or swapped):
            break
    return _tidy(text), _tidy(text) != original


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    paths = [pathlib.Path(p) for p in argv] if argv else sorted(CASK_DIR.glob("*.rb"))

    changed = []
    for path in paths:
        text = original = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in text:
            continue
        text, did_change = normalise(text)
        if did_change and text != original:
            path.write_text(text, encoding="utf-8")
            changed.append(path.name)

    if changed:
        print(f"Normalised {len(changed)} cask(s): {', '.join(changed)}")
    else:
        print("No casks needed normalising.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
